app:
  name: "wb-tech-test-assignment"
log:
  level: "debug"
  format_json: false
  rotation:
    file: "./test-assignment.log"
    max_size: 10
    max_backups: 3
    max_age: 7
database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "admin"
  name: "wb-tech-test-assignment"
  ssl_mode: "disable"
  max_conns: 10
  min_conns: 2
  migration:
    path: "./migrations"
    auto_apply: true
